version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes: 
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    command: bash -c "ollama server && ollama run llama3"

  repo-copilot:
    build: ./
    ports:
      - "80:8080"
    volumes:
      - ./:/repo-copilot
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    depends_on:
      - ollama

volumes:
  ollama: