name: Deploy Website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone website repository
        run: git clone https://github.com/ucl-repo-copilot/ucl-repo-copilot.github.io.git ../repo-website

      - name: Install dependencies
        run: cd website && npm ci

      - name: Build website
        run: cd website && npm run build

      - name: Commit and push changes
        run: |
          cp -r website/dist/* ../repo-website
          cd ../repo-website
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git add .
          if git commit -m "Update website"; then
            git push https://${{ secrets.TOKEN }}@github.com/ucl-repo-copilot/ucl-repo-copilot.github.io.git HEAD:main
          else
            echo "No changes detected, skipping push."
          fi
